### PR TITLE
Create a 1s interval timer for playlist checks

### PR DESCRIPTION
**Pull request by alex-deaconu**
## Description
Create a 1s interval timer for playlist checks

Initially used for playlist item operation
Designed to be reused for timeline checks

Remove original setTimeout

## Motivation and Context
In preparation to Add Timeline to Playlist Items.

## How Has This Been Tested?
Tested locally with Charles

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Review by ezequielc — APPROVED** [review]
@alex-deaconu Looks good to me 👍

**Comment by alex-deaconu** [comment]
@ezequielc as discussed, I've removed the link between the timeline timer and the playback mechanism. It will function on its own to prevent issues. Please review the second commit, as well as the update to https://github.com/Rise-Vision/rise-playlist-new/pull/68. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I reviewed and looks good 👍  Thanks!

**Comment by alex-deaconu** [comment]
@stulees @olegrise wondering if you could review as well.

As a pre-cursor to the Timeline implementation for Playlist Items, we have added a 1 second interval to be used for playlist checks.

This prevents the use and management of multiple timeouts for item and timeline checks. It also abstracts the 1s tick functionality so an external common interval can be used to synchronize content.

This implementation is very similar to what Viewer already uses for its playlists [for example](https://github.com/Rise-Vision/viewer/blob/master/src-js/Viewer/Content/PlaceholderController.js#L216-L237).

Thanks!

**Comment by alex-deaconu** [comment]
@stulees our plan is to release each iteration to stable, not just master. @ezequielc fyi. Thanks!

**Pull request merged**
